#!/bin/bash
export XDEBUG_CONFIG="idekey=phpMQTT-debug"
php -dxdebug.remote_enable=1 -dxdebug.remote_mode=req -dxdebug.remote_port=9000 -dxdebug.remote_host=127.0.0.1 -dxdebug.remote_connect_back=1 ${@:1}

